### ISSUE TITLE
Suggested export options tweaks

### ISSUE THREAD

**Issue by donmccurdy** [looeee/blackthread_hugo#2]
Couple quick suggestions for export options -

* [ ] Binary (.glb) or ASCII (.gltf)

^it's not clear to me at a glance that 'checked' means binary and unchecked means ASCII. Maybe a dropdown, or different phrasing like `Export binary (.glb). Default is ASCII (.gltf)`. Technically default could contain UTF8 as well but not sure it's worth mentioning that. 😅

* Export position, rotation and scale instead of matrix per node

I don't know why we have this option actually, probably no need to expose it 

* Export just the attributes within the drawRange, if defined, instead of exporting the whole array

is it possible to load a model that includes its own draw range? I'm not sure how to do that. If not, probably can't use this option.

May also want to add `forceIndices`, since I think facebook currently requires that.

Nice work! 👏

**Comment by looeee** [comment]
Thanks for the feedback 😄 

The "export" button changes to say "Export as GLB" or "Export as GLTF" depending on whether the checkbox is ticked. 

> * Export position, rotation and scale instead of matrix per node
> * Export just the attributes within the drawRange, if defined, instead of exporting the whole array

> is it possible to load a model that includes its own draw range?

I would say, probably not. I'll remove these options. 

> May also want to add forceIndices, since I think facebook currently requires that.

This is already set, but hidden from the user. I'll remove the other two options and expose this one instead.

**Comment by looeee** [comment]
OK, I've updated the options - they should be clearer now.

**Comment by donmccurdy** [comment]
Looks great!
